package handlers

import (
	"encoding/json"
	"net/http"
	"symbol-web/internal/ai"
)

type AIHandler struct {
	Client *ai.Client
}

func NewAiHandler(client *ai.Client) *AIHandler {
	return &AIHandler{Client: client}
}
func WriteJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(payload); err != nil {
		http.Error(w, "Failed to encode JSON response", http.StatusInternalServerError)
	}
}
func writeJSONError(w http.ResponseWriter, status int, message string) {
	WriteJSON(w, status, errorResponse{Error: message})
}

type textRequest struct {
	Text string `json:"text"`
}
type suggestResponse struct {
	Suggestions []string `json:"suggestions"`
}
type errorResponse struct {
	Error string `json:"error"`
}
type variationsResponse struct {
	Variations []ai.Variation `json:"variations"`
}

func decodeTextRequest(w http.ResponseWriter, r *http.Request) (string, bool) {
	if r.Method != http.MethodPost {
		writeJSONError(w, http.StatusMethodNotAllowed, "Method not allowed")
		return "", false
	}
	var req textRequest
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		writeJSONError(w, http.StatusBadRequest, "Invalid request body")
		return "", false
	}
	if len(req.Text) > 1000 {
		writeJSONError(w, http.StatusBadRequest, "Text exceeds maximum length of 1000 characters")
		return "", false
	}
	return req.Text, true
}

// Suggest accepts a prompt via POST and returns suggestions generated by the LLM.
func (h *AIHandler) Suggest(w http.ResponseWriter, r *http.Request) {
	text, ok := decodeTextRequest(w, r)
	if !ok {
		return
	}
	if len(text) < ai.MinSuggestInputLength {
		writeJSONError(w, http.StatusBadRequest, "Text must be at least 3 characters long")
		return
	}
	suggestions, err := h.Client.GetSuggestions(r.Context(), text)
	if err != nil {
		handleAIError(w, err, "suggest")
		return

	}
	WriteJSON(w, http.StatusOK, suggestResponse{Suggestions: suggestions})
}
func (h *AIHandler) RecommendBanner(w http.ResponseWriter, r *http.Request) {
	text, ok := decodeTextRequest(w, r)
	if !ok {
		return
	}
	if text == "" {
		writeJSONError(w, http.StatusBadRequest, "text must not be empty")
		return
	}

	recommendation := ai.Recommend(text)
	WriteJSON(w, http.StatusOK, recommendation)
}
func (h *AIHandler) Variations(w http.ResponseWriter, r *http.Request) {
	text, ok := decodeTextRequest(w, r)
	if !ok {
		return
	}
	if text == "" {
		writeJSONError(w, http.StatusBadRequest, "text must not be empty")
		return
	}

	variations, err := h.Client.GetVariations(r.Context(), text)
	if err != nil {
		handleAIError(w, err, "variations")
		return
	}

	WriteJSON(w, http.StatusOK, variationsResponse{Variations: variations})
}
func handleAIError(w http.ResponseWriter, err error, endpoint string) {
	if err == ai.ErrBackendUnavailable {
		writeJSONError(w, http.StatusServiceUnavailable, "AI backend unavailable for "+endpoint)
	} else if err == ai.ErrBadResponse {
		writeJSONError(w, http.StatusInternalServerError, "AI backend returned bad response for "+endpoint)
	} else {
		writeJSONError(w, http.StatusInternalServerError, "Unexpected error for "+endpoint+": "+err.Error())
	}
}
